
import java.awt.Color;
import java.awt.Cursor;
import java.time.format.DateTimeFormatter;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/*
 * User Interface Klasse
 * De gebruiker activeert zijn account door zijn rijksregisternummer
 * in te geven en ontvangt per email zijn gegevens. (simulatie van de werking
 * van een websitedienst van de overheid)
 * Na inloggen met de juiste gegevens krijgt de ouder toegang tot zijn
 * elektronische documenten 
 * Onder de 'Aanmeldingsformulier'-tab wordt een aanvraag ingediend,
 * een voorkeur kan aangepast worden onder de 'Voorkeurformulier'-tab 
 * en onder de 'Aanvragen raadplegen'-tab wordt informatie gegeven
 * over de lopende aanvragen
 *
 * @author Boris Dragnev, Victor Masscho, Jean Janssens, Edith Lust, Job van Lambalgen
 */
public class UI extends javax.swing.JFrame  {
  
    private Main main;
    private Ouder gebruiker;
    private final DefaultTableModel dtm;
    private School[] scholenData;
    
    public UI(Main main) {
      this.main = main; 
      initComponents(); //componenten van NetBeans GuiBuilder initializeren
      getContentPane().setBackground(Color.white); //wit achtergrond van de Pane
      InlogScherm.getRootPane().setDefaultButton(inlogKnopIS);


      scholenData = main.ophalenScholen();

      /*
       * Scholen toevoegen aan de tabel onder de 'Voorkeurformulier'-tab
       */
      this.dtm = (DefaultTableModel)scholenTabel.getModel();
      for (School s : scholenData) {
	  Object[] o = new Object[4];
	  o[0] = s.getNaam();
	  o[1] = s.getAdres();
	  o[2] = s.getPlaatsen();
	  o[3] = s.getID();
	  dtm.addRow(o);
      }

      /*
       * Methode dat de actie bepaalt bij het selecteren van een item uit
       * tabel met scholen
       */
      scholenTabel.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
	@Override
	public void valueChanged(ListSelectionEvent e) {
	  if(scholenTabel.getSelectedRow() > -1) {
	      selectieBoodschapLabel.setForeground(Color.BLACK);
	      selectieBoodschapLabel.setText("U heeft een school "
		      + "geselecteerd.");
	  } else {
	      selectieBoodschapLabel.setForeground(Color.red);
	      selectieBoodschapLabel.setText("Gelieve een school uit de "
		      + "bovenstaande lijst te "
		      + "selecteren.");
	  }
	}
      });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    MainPanel = new javax.swing.JPanel();
    InlogScherm = new javax.swing.JPanel();
    gebrLabelAS = new javax.swing.JLabel();
    gebrVeldIS = new javax.swing.JTextField();
    passVeldIS = new javax.swing.JPasswordField();
    passLabelIS = new javax.swing.JLabel();
    inlogKnopIS = new javax.swing.JButton();
    activeerLinkLabelIS = new javax.swing.JLabel();
    boodschapLabelIS = new javax.swing.JLabel();
    doorgaanKnopIS = new javax.swing.JButton();
    logoLabel = new javax.swing.JLabel();
    ActiveerScherm = new javax.swing.JPanel();
    gegevensOuderAS = new javax.swing.JPanel();
    naamLabelAS = new javax.swing.JLabel();
    voornaamLabelAS = new javax.swing.JLabel();
    rijksnumLabelAS = new javax.swing.JLabel();
    emailLabelAS = new javax.swing.JLabel();
    adresLabelAS = new javax.swing.JLabel();
    rijksnumVeldAS = new javax.swing.JTextField();
    naamVeldAS = new javax.swing.JTextField();
    voornaamVeldAS = new javax.swing.JTextField();
    emailVeldAS = new javax.swing.JTextField();
    adresVeldAS = new javax.swing.JTextField();
    terugLinkLabelAS = new javax.swing.JLabel();
    activeerKnopAS = new javax.swing.JButton();
    boodschapLabelAS = new javax.swing.JLabel();
    logoLabel1 = new javax.swing.JLabel();
    FormulierScherm = new javax.swing.JTabbedPane();
    HomeTab = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jPanel4 = new javax.swing.JPanel();
    AlgemeneTekstOuders = new javax.swing.JLabel();
    PersoonlijkeJlabel = new javax.swing.JLabel();
    volgendeTabKnop = new javax.swing.JButton();
    AanmeldingsFormulierTab = new javax.swing.JPanel();
    indienenKnopAFT = new javax.swing.JButton();
    gegevensStudentAFT = new javax.swing.JPanel();
    naamStudentLabelAFT = new javax.swing.JLabel();
    voornaamStudentLabelAFT = new javax.swing.JLabel();
    rijksnumStudentLabelAFT = new javax.swing.JLabel();
    telnumLabelAFT = new javax.swing.JLabel();
    naamStudentVeldAFT = new javax.swing.JTextField();
    voornaamStudentVeldAFT = new javax.swing.JTextField();
    telnumVeldAFT = new javax.swing.JTextField();
    studentenDropBoxAFT = new javax.swing.JComboBox<>();
    gegevensOuderAFT = new javax.swing.JPanel();
    naamOuderLabelAFT = new javax.swing.JLabel();
    voornaamOuderLabelAFT = new javax.swing.JLabel();
    rijksnumOuderLabelAFT = new javax.swing.JLabel();
    emailLabelAFT = new javax.swing.JLabel();
    adresLabelAFT = new javax.swing.JLabel();
    rijksnumOuderVeldAFT = new javax.swing.JTextField();
    naamOuderVeldAFT = new javax.swing.JTextField();
    voornaamOuderVeldAFT = new javax.swing.JTextField();
    emailVeldAFT = new javax.swing.JTextField();
    adresVeldAFT = new javax.swing.JTextField();
    boodschapLabelAFT = new javax.swing.JLabel();
    waarschuwingLabelAFT = new javax.swing.JLabel();
    VoorkeurFormulierTab = new javax.swing.JPanel();
    zoekwoordLabel = new javax.swing.JLabel();
    zoekwoordVeld = new javax.swing.JTextField();
    indienenKnopVFT = new javax.swing.JButton();
    selectieBoodschapLabel = new javax.swing.JLabel();
    rijksnumStudentLabelVFT = new javax.swing.JLabel();
    infoLabelVFT = new javax.swing.JLabel();
    scholenScrollPane = new javax.swing.JScrollPane();
    scholenTabel = new javax.swing.JTable();
    boodschapLabelVFT = new javax.swing.JLabel();
    studentenDropBoxVFT = new javax.swing.JComboBox<>();
    aanvraagNummerLabelVFT = new javax.swing.JLabel();
    aanvraagnummerVeldVFT = new javax.swing.JTextField();
    ZoekAanvraagTab = new javax.swing.JPanel();
    rijksnumStudentLabelART = new javax.swing.JLabel();
    infoLabelART = new javax.swing.JLabel();
    gegevensPanelART = new javax.swing.JPanel();
    eersteVoorkeurLabel = new javax.swing.JLabel();
    aanvraagnummerLabelOut = new javax.swing.JLabel();
    statusLabelOut = new javax.swing.JLabel();
    tijdstipLabelOut = new javax.swing.JLabel();
    eersteVoorkeurLabelOut = new javax.swing.JLabel();
    aanvraagnummerLabelART = new javax.swing.JLabel();
    statusLabel = new javax.swing.JLabel();
    tijdstipLabel = new javax.swing.JLabel();
    studentenDropBoxART = new javax.swing.JComboBox<>();
    verwijderLinkLabelART = new javax.swing.JLabel();
    boodschapLabelART = new javax.swing.JLabel();
    UitloggenTab = new javax.swing.JPanel();
    uitloggenLinkLabel = new javax.swing.JLabel();
    AdminScherm = new javax.swing.JPanel();
    jPanel1 = new javax.swing.JPanel();
    exporteerKnopAdmin = new javax.swing.JButton();
    sorteerKnopAdmin = new javax.swing.JButton();
    jPanel3 = new javax.swing.JPanel();
    wachtlijstScrollPane = new javax.swing.JScrollPane();
    jList1 = new javax.swing.JList<>();
    wachtlijstLadenKnop = new javax.swing.JButton();
    wachtLijstNaamVeld = new javax.swing.JTextField();
    wachtLijstNaamLabel = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Centrale toewijzing leerlingen");
    setBackground(new java.awt.Color(255, 255, 255));
    setExtendedState(MAXIMIZED_BOTH);
    setSize(new java.awt.Dimension(0, 0));
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosing(java.awt.event.WindowEvent evt) {
        onClose(evt);
      }
    });
    getContentPane().setLayout(new java.awt.GridBagLayout());

    MainPanel.setBackground(new java.awt.Color(255, 255, 255));
    MainPanel.setPreferredSize(new java.awt.Dimension(800, 800));
    MainPanel.setLayout(new java.awt.CardLayout());

    InlogScherm.setBackground(new java.awt.Color(255, 255, 255));
    InlogScherm.setPreferredSize(new java.awt.Dimension(800, 800));

    gebrLabelAS.setText("Gebruikersnaam:");

    passLabelIS.setBackground(new java.awt.Color(0, 0, 0));
    passLabelIS.setText("Wachtwoord:");

    inlogKnopIS.setText("Inloggen");
    inlogKnopIS.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        inlogKnopISActionPerformed(evt);
      }
    });

    activeerLinkLabelIS.setForeground(new java.awt.Color(0, 102, 255));
    activeerLinkLabelIS.setText("Uw account activeren");
    activeerLinkLabelIS.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        activeerLinkLabelISMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        activeerLinkLabelISMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        activeerLinkLabelISMouseExited(evt);
      }
    });

    boodschapLabelIS.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

    doorgaanKnopIS.setText("Doorgaan");
    doorgaanKnopIS.setEnabled(false);
    doorgaanKnopIS.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        doorgaanKnopISActionPerformed(evt);
      }
    });

    logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N

    javax.swing.GroupLayout InlogSchermLayout = new javax.swing.GroupLayout(InlogScherm);
    InlogScherm.setLayout(InlogSchermLayout);
    InlogSchermLayout.setHorizontalGroup(
      InlogSchermLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(InlogSchermLayout.createSequentialGroup()
        .addContainerGap(280, Short.MAX_VALUE)
        .addGroup(InlogSchermLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(InlogSchermLayout.createSequentialGroup()
            .addComponent(boodschapLabelIS, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(doorgaanKnopIS))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InlogSchermLayout.createSequentialGroup()
            .addComponent(activeerLinkLabelIS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(inlogKnopIS, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InlogSchermLayout.createSequentialGroup()
            .addGroup(InlogSchermLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(gebrLabelAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(passLabelIS, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(InlogSchermLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(passVeldIS, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
              .addComponent(gebrVeldIS))))
        .addGap(33, 281, Short.MAX_VALUE))
      .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    InlogSchermLayout.setVerticalGroup(
      InlogSchermLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(InlogSchermLayout.createSequentialGroup()
        .addGap(32, 32, 32)
        .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(26, 26, 26)
        .addGroup(InlogSchermLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(gebrLabelAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(gebrVeldIS))
        .addGap(9, 9, 9)
        .addGroup(InlogSchermLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(passLabelIS, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(passVeldIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(InlogSchermLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(activeerLinkLabelIS)
          .addComponent(inlogKnopIS))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(InlogSchermLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(boodschapLabelIS, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(doorgaanKnopIS))
        .addGap(263, 263, 263))
    );

    MainPanel.add(InlogScherm, "card5");

    ActiveerScherm.setBackground(new java.awt.Color(255, 255, 255));
    ActiveerScherm.setPreferredSize(new java.awt.Dimension(800, 800));

    gegevensOuderAS.setBackground(new java.awt.Color(255, 255, 255));
    gegevensOuderAS.setBorder(javax.swing.BorderFactory.createTitledBorder("Ouder"));

    naamLabelAS.setText("Naam:");

    voornaamLabelAS.setText("Voornaam:");

    rijksnumLabelAS.setText("Rijksregisternummer:");

    emailLabelAS.setText("E-mail:");

    adresLabelAS.setText("Adres:");

    rijksnumVeldAS.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        rijksnumVeldASKeyReleased(evt);
      }
    });

    naamVeldAS.setFocusable(false);

    voornaamVeldAS.setFocusable(false);

    emailVeldAS.setFocusable(false);

    adresVeldAS.setFocusable(false);

    javax.swing.GroupLayout gegevensOuderASLayout = new javax.swing.GroupLayout(gegevensOuderAS);
    gegevensOuderAS.setLayout(gegevensOuderASLayout);
    gegevensOuderASLayout.setHorizontalGroup(
      gegevensOuderASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(gegevensOuderASLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(gegevensOuderASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(gegevensOuderASLayout.createSequentialGroup()
            .addGroup(gegevensOuderASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(naamLabelAS)
              .addComponent(emailLabelAS)
              .addComponent(adresLabelAS))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(gegevensOuderASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(naamVeldAS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(emailVeldAS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(adresVeldAS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(gegevensOuderASLayout.createSequentialGroup()
            .addComponent(voornaamLabelAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(voornaamVeldAS, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(gegevensOuderASLayout.createSequentialGroup()
            .addComponent(rijksnumLabelAS)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(rijksnumVeldAS, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    gegevensOuderASLayout.setVerticalGroup(
      gegevensOuderASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(gegevensOuderASLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(gegevensOuderASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(rijksnumVeldAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gegevensOuderASLayout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(rijksnumLabelAS)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(gegevensOuderASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(naamLabelAS)
          .addComponent(naamVeldAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(gegevensOuderASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(voornaamLabelAS)
          .addComponent(voornaamVeldAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(gegevensOuderASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(emailLabelAS)
          .addComponent(emailVeldAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(gegevensOuderASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(adresLabelAS)
          .addComponent(adresVeldAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(35, Short.MAX_VALUE))
    );

    terugLinkLabelAS.setForeground(new java.awt.Color(0, 102, 255));
    terugLinkLabelAS.setText("Terug");
    terugLinkLabelAS.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        terugLinkLabelASMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        terugLinkLabelASMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        terugLinkLabelASMouseExited(evt);
      }
    });

    activeerKnopAS.setText("Activeren");
    activeerKnopAS.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        activeerKnopASActionPerformed(evt);
      }
    });

    logoLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    logoLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N

    javax.swing.GroupLayout ActiveerSchermLayout = new javax.swing.GroupLayout(ActiveerScherm);
    ActiveerScherm.setLayout(ActiveerSchermLayout);
    ActiveerSchermLayout.setHorizontalGroup(
      ActiveerSchermLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(ActiveerSchermLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(ActiveerSchermLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(boodschapLabelAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ActiveerSchermLayout.createSequentialGroup()
            .addComponent(terugLinkLabelAS)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(activeerKnopAS))
          .addComponent(gegevensOuderAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ActiveerSchermLayout.createSequentialGroup()
        .addComponent(logoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1019, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    ActiveerSchermLayout.setVerticalGroup(
      ActiveerSchermLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ActiveerSchermLayout.createSequentialGroup()
        .addGap(38, 38, 38)
        .addComponent(logoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(27, 27, 27)
        .addComponent(gegevensOuderAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(boodschapLabelAS, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(ActiveerSchermLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(terugLinkLabelAS)
          .addComponent(activeerKnopAS))
        .addContainerGap(281, Short.MAX_VALUE))
    );

    MainPanel.add(ActiveerScherm, "card4");

    FormulierScherm.setBackground(new java.awt.Color(255, 255, 255));
    FormulierScherm.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    FormulierScherm.setPreferredSize(new java.awt.Dimension(800, 800));
    FormulierScherm.addChangeListener(new javax.swing.event.ChangeListener() {
      public void stateChanged(javax.swing.event.ChangeEvent evt) {
        FormulierSchermStateChanged(evt);
      }
    });

    jPanel4.setBackground(new java.awt.Color(255, 255, 255));

    AlgemeneTekstOuders.setText("<html>Sinds een aantal jaren komt de vraag naar plaatsen voor het basisonderwijs<br/> \nniet overeen met het aanbod. Recent ziet men ook hetzelfde probleem bij<br/> \nplaatsen voor het middelbaar onderwijs. Beide problemen manifesteren<br/>\nzich voornamelijk in de grotere steden. Bijgevolg hebben we een online<br/> \ninformatiesysteem ontwikkeld om de centrale toewijzing van kinderen aan<br/>\nscholen te regelen. <br/>\n<br/>\nDe werking van ons informatiesysteem is grotendeels gebaseerd op de tijd<br/> \nvan aanmelding in het systeem, de school die geprefereerd wordt en of er<br/> \nal dan niet broers of zussen reeds op die school zitten. <br/>\n<br/>\nIn het volgende tabblad kan u uw aanmeldingsformulier invullen en<br/>\nvervolgens ook een voorkeursformulier. \n</html>");

    PersoonlijkeJlabel.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
    PersoonlijkeJlabel.setText("jLabel4");

    volgendeTabKnop.setText("Volgende");
    volgendeTabKnop.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        volgendeTabKnopActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addGap(40, 40, 40)
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
          .addComponent(volgendeTabKnop)
          .addGroup(jPanel4Layout.createSequentialGroup()
            .addComponent(PersoonlijkeJlabel)
            .addGap(316, 316, 316))
          .addComponent(AlgemeneTekstOuders))
        .addGap(0, 0, 0))
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addGap(12, 12, 12)
        .addComponent(PersoonlijkeJlabel)
        .addGap(18, 18, 18)
        .addComponent(AlgemeneTekstOuders, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(volgendeTabKnop)
        .addContainerGap(889, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout HomeTabLayout = new javax.swing.GroupLayout(HomeTab);
    HomeTab.setLayout(HomeTabLayout);
    HomeTabLayout.setHorizontalGroup(
      HomeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(HomeTabLayout.createSequentialGroup()
        .addGap(67, 67, 67)
        .addComponent(jLabel2)
        .addContainerGap(724, Short.MAX_VALUE))
      .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    HomeTabLayout.setVerticalGroup(
      HomeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(HomeTabLayout.createSequentialGroup()
        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel2)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    FormulierScherm.addTab("Home", HomeTab);

    AanmeldingsFormulierTab.setBackground(new java.awt.Color(255, 255, 255));
    AanmeldingsFormulierTab.setBorder(javax.swing.BorderFactory.createTitledBorder("Student"));

    indienenKnopAFT.setText("Indienen");
    indienenKnopAFT.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        indienenKnopAFTActionPerformed(evt);
      }
    });

    gegevensStudentAFT.setBackground(new java.awt.Color(255, 255, 255));
    gegevensStudentAFT.setBorder(javax.swing.BorderFactory.createTitledBorder("Student"));

    naamStudentLabelAFT.setText("Naam:");

    voornaamStudentLabelAFT.setText("Voornaam:");

    rijksnumStudentLabelAFT.setText("Rijksregisternummer:");

    telnumLabelAFT.setText("Telefoonnummer:");

    naamStudentVeldAFT.setFocusable(false);

    voornaamStudentVeldAFT.setFocusable(false);

    telnumVeldAFT.setFocusable(false);

    studentenDropBoxAFT.setModel(new DefaultComboBoxModel());
    studentenDropBoxAFT.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        studentenDropBoxAFTItemStateChanged(evt);
      }
    });

    javax.swing.GroupLayout gegevensStudentAFTLayout = new javax.swing.GroupLayout(gegevensStudentAFT);
    gegevensStudentAFT.setLayout(gegevensStudentAFTLayout);
    gegevensStudentAFTLayout.setHorizontalGroup(
      gegevensStudentAFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(gegevensStudentAFTLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(gegevensStudentAFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(naamStudentLabelAFT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(voornaamStudentLabelAFT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(telnumLabelAFT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(rijksnumStudentLabelAFT))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(gegevensStudentAFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(voornaamStudentVeldAFT, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(studentenDropBoxAFT, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(naamStudentVeldAFT, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(telnumVeldAFT, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(209, Short.MAX_VALUE))
    );
    gegevensStudentAFTLayout.setVerticalGroup(
      gegevensStudentAFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(gegevensStudentAFTLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(gegevensStudentAFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(rijksnumStudentLabelAFT)
          .addComponent(studentenDropBoxAFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(gegevensStudentAFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(voornaamStudentLabelAFT)
          .addComponent(voornaamStudentVeldAFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(gegevensStudentAFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(naamStudentLabelAFT)
          .addComponent(naamStudentVeldAFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(gegevensStudentAFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(telnumLabelAFT)
          .addComponent(telnumVeldAFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    gegevensOuderAFT.setBackground(new java.awt.Color(255, 255, 255));
    gegevensOuderAFT.setBorder(javax.swing.BorderFactory.createTitledBorder("Ouder"));

    naamOuderLabelAFT.setText("Naam:");

    voornaamOuderLabelAFT.setText("Voornaam:");

    rijksnumOuderLabelAFT.setText("Rijksregisternummer:");

    emailLabelAFT.setText("E-mail:");

    adresLabelAFT.setText("Adres:");

    rijksnumOuderVeldAFT.setFocusable(false);

    naamOuderVeldAFT.setFocusable(false);

    voornaamOuderVeldAFT.setFocusable(false);

    emailVeldAFT.setFocusable(false);

    adresVeldAFT.setFocusable(false);

    javax.swing.GroupLayout gegevensOuderAFTLayout = new javax.swing.GroupLayout(gegevensOuderAFT);
    gegevensOuderAFT.setLayout(gegevensOuderAFTLayout);
    gegevensOuderAFTLayout.setHorizontalGroup(
      gegevensOuderAFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(gegevensOuderAFTLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(gegevensOuderAFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(gegevensOuderAFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addComponent(emailLabelAFT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(naamOuderLabelAFT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(voornaamOuderLabelAFT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rijksnumOuderLabelAFT, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
          .addComponent(adresLabelAFT, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(gegevensOuderAFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(voornaamOuderVeldAFT, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
          .addComponent(naamOuderVeldAFT)
          .addComponent(rijksnumOuderVeldAFT)
          .addComponent(emailVeldAFT)
          .addComponent(adresVeldAFT))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    gegevensOuderAFTLayout.setVerticalGroup(
      gegevensOuderAFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(gegevensOuderAFTLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(gegevensOuderAFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(voornaamOuderLabelAFT)
          .addComponent(voornaamOuderVeldAFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(gegevensOuderAFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(naamOuderVeldAFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(naamOuderLabelAFT))
        .addGap(18, 18, 18)
        .addGroup(gegevensOuderAFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(rijksnumOuderLabelAFT)
          .addComponent(rijksnumOuderVeldAFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(20, 20, 20)
        .addGroup(gegevensOuderAFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(emailLabelAFT)
          .addComponent(emailVeldAFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(gegevensOuderAFTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(adresLabelAFT)
          .addComponent(adresVeldAFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(0, 10, Short.MAX_VALUE))
    );

    boodschapLabelAFT.setForeground(new java.awt.Color(255, 0, 0));
    boodschapLabelAFT.setVerticalAlignment(javax.swing.SwingConstants.TOP);

    waarschuwingLabelAFT.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
    waarschuwingLabelAFT.setText("Alle aanvragen dienen vóór 15 juli ingediend te worden!");

    javax.swing.GroupLayout AanmeldingsFormulierTabLayout = new javax.swing.GroupLayout(AanmeldingsFormulierTab);
    AanmeldingsFormulierTab.setLayout(AanmeldingsFormulierTabLayout);
    AanmeldingsFormulierTabLayout.setHorizontalGroup(
      AanmeldingsFormulierTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(AanmeldingsFormulierTabLayout.createSequentialGroup()
        .addGroup(AanmeldingsFormulierTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(AanmeldingsFormulierTabLayout.createSequentialGroup()
            .addGap(12, 12, 12)
            .addComponent(waarschuwingLabelAFT))
          .addGroup(AanmeldingsFormulierTabLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(AanmeldingsFormulierTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addComponent(gegevensStudentAFT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(indienenKnopAFT)
              .addComponent(gegevensOuderAFT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(boodschapLabelAFT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        .addContainerGap())
    );
    AanmeldingsFormulierTabLayout.setVerticalGroup(
      AanmeldingsFormulierTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(AanmeldingsFormulierTabLayout.createSequentialGroup()
        .addComponent(waarschuwingLabelAFT)
        .addGap(6, 6, 6)
        .addComponent(gegevensStudentAFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(12, 12, 12)
        .addComponent(gegevensOuderAFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(boodschapLabelAFT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(indienenKnopAFT)
        .addContainerGap())
    );

    FormulierScherm.addTab("Aanmeldingsformulier", AanmeldingsFormulierTab);

    VoorkeurFormulierTab.setBackground(new java.awt.Color(255, 255, 255));
    VoorkeurFormulierTab.setBorder(javax.swing.BorderFactory.createTitledBorder("School"));

    zoekwoordLabel.setText("Zoekwoord:");

    zoekwoordVeld.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        zoekwoordVeldKeyReleased(evt);
      }
    });

    indienenKnopVFT.setText("Indienen");
    indienenKnopVFT.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        indienenKnopVFTActionPerformed(evt);
      }
    });

    selectieBoodschapLabel.setForeground(new java.awt.Color(255, 0, 0));
    selectieBoodschapLabel.setText("Gelieve een school uit de bovenstaande lijst te selecteren.");
    selectieBoodschapLabel.setToolTipText("");
    selectieBoodschapLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

    rijksnumStudentLabelVFT.setText("Rijksregisternummer (kind):");

    infoLabelVFT.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
    infoLabelVFT.setText("<html>Deze formulier past uw keuze aan voor de lopende periode.<br/> U kunt uw eerste voorkeur aanpassen vóór 15 juli.</html>");

    scholenTabel.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Naam", "Adres", "Capaciteit", "ID"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    scholenScrollPane.setViewportView(scholenTabel);

    boodschapLabelVFT.setVerticalAlignment(javax.swing.SwingConstants.TOP);

    studentenDropBoxVFT.setModel(new DefaultComboBoxModel());
    studentenDropBoxVFT.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        studentenDropBoxVFTItemStateChanged(evt);
      }
    });

    aanvraagNummerLabelVFT.setText("Toewijzingsaanvraagnummer:");

    aanvraagnummerVeldVFT.setFocusable(false);

    javax.swing.GroupLayout VoorkeurFormulierTabLayout = new javax.swing.GroupLayout(VoorkeurFormulierTab);
    VoorkeurFormulierTab.setLayout(VoorkeurFormulierTabLayout);
    VoorkeurFormulierTabLayout.setHorizontalGroup(
      VoorkeurFormulierTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(VoorkeurFormulierTabLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(VoorkeurFormulierTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(selectieBoodschapLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
          .addComponent(infoLabelVFT, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(VoorkeurFormulierTabLayout.createSequentialGroup()
            .addComponent(boodschapLabelVFT, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(indienenKnopVFT))
          .addGroup(VoorkeurFormulierTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, VoorkeurFormulierTabLayout.createSequentialGroup()
              .addComponent(zoekwoordLabel)
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addComponent(zoekwoordVeld))
            .addComponent(scholenScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, VoorkeurFormulierTabLayout.createSequentialGroup()
              .addGroup(VoorkeurFormulierTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(aanvraagNummerLabelVFT)
                .addComponent(rijksnumStudentLabelVFT))
              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
              .addGroup(VoorkeurFormulierTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(studentenDropBoxVFT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aanvraagnummerVeldVFT))))))
    );
    VoorkeurFormulierTabLayout.setVerticalGroup(
      VoorkeurFormulierTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(VoorkeurFormulierTabLayout.createSequentialGroup()
        .addComponent(infoLabelVFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(VoorkeurFormulierTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(rijksnumStudentLabelVFT)
          .addComponent(studentenDropBoxVFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(27, 27, 27)
        .addGroup(VoorkeurFormulierTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(aanvraagNummerLabelVFT)
          .addComponent(aanvraagnummerVeldVFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(22, 22, 22)
        .addGroup(VoorkeurFormulierTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(zoekwoordLabel)
          .addComponent(zoekwoordVeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(scholenScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(selectieBoodschapLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(14, 14, 14)
        .addGroup(VoorkeurFormulierTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(boodschapLabelVFT, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(indienenKnopVFT))
        .addContainerGap(835, Short.MAX_VALUE))
    );

    FormulierScherm.addTab("Voorkeurformulier", VoorkeurFormulierTab);

    ZoekAanvraagTab.setBackground(new java.awt.Color(255, 255, 255));

    rijksnumStudentLabelART.setText("Rijksregisternummer (kind): ");

    infoLabelART.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
    infoLabelART.setText("<html>Je kan je aanvragen onderaan raadplegen door het rijksregisternummer van uw kind in te\n <br/>geven. Mocht u niet tevreden zijn met uw opgegeven voorkeur, kunt u deze nog aanpassen\n<br/>door opnieuw de 'Voorkeurformulier' in te vullen.\n<br/>(Let op: u kan enkel de voorkeur voor de lopende periode aanpassen!)</html>");

    gegevensPanelART.setBackground(new java.awt.Color(255, 255, 255));
    gegevensPanelART.setBorder(javax.swing.BorderFactory.createTitledBorder("Uw gegevens"));

    eersteVoorkeurLabel.setText("Voorkeurschool:");

    aanvraagnummerLabelART.setText("Aanvraagnummer:");

    statusLabel.setText("Status:");

    tijdstipLabel.setText("Tijdstip van aanmelding:");

    javax.swing.GroupLayout gegevensPanelARTLayout = new javax.swing.GroupLayout(gegevensPanelART);
    gegevensPanelART.setLayout(gegevensPanelARTLayout);
    gegevensPanelARTLayout.setHorizontalGroup(
      gegevensPanelARTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(gegevensPanelARTLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(gegevensPanelARTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(aanvraagnummerLabelART)
          .addComponent(tijdstipLabel)
          .addComponent(eersteVoorkeurLabel)
          .addComponent(statusLabel))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(gegevensPanelARTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(aanvraagnummerLabelOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(statusLabelOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(tijdstipLabelOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(eersteVoorkeurLabelOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    gegevensPanelARTLayout.setVerticalGroup(
      gegevensPanelARTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(gegevensPanelARTLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(gegevensPanelARTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(aanvraagnummerLabelART)
          .addComponent(aanvraagnummerLabelOut, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(gegevensPanelARTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(statusLabel)
          .addComponent(statusLabelOut, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(gegevensPanelARTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(tijdstipLabel)
          .addComponent(tijdstipLabelOut, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(gegevensPanelARTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(eersteVoorkeurLabel)
          .addComponent(eersteVoorkeurLabelOut, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    studentenDropBoxART.setModel(new DefaultComboBoxModel());
    studentenDropBoxART.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        studentenDropBoxARTItemStateChanged(evt);
      }
    });

    verwijderLinkLabelART.setFont(new java.awt.Font("Dialog", 2, 11)); // NOI18N
    verwijderLinkLabelART.setForeground(java.awt.Color.blue);
    verwijderLinkLabelART.setText("<html><u>VERWIJDEREN</u></html>");
    verwijderLinkLabelART.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        verwijderLinkLabelARTMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        verwijderLinkLabelARTMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        verwijderLinkLabelARTMouseExited(evt);
      }
    });

    boodschapLabelART.setText("boodschapLabelART");

    javax.swing.GroupLayout ZoekAanvraagTabLayout = new javax.swing.GroupLayout(ZoekAanvraagTab);
    ZoekAanvraagTab.setLayout(ZoekAanvraagTabLayout);
    ZoekAanvraagTabLayout.setHorizontalGroup(
      ZoekAanvraagTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(ZoekAanvraagTabLayout.createSequentialGroup()
        .addGroup(ZoekAanvraagTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(boodschapLabelART, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(ZoekAanvraagTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ZoekAanvraagTabLayout.createSequentialGroup()
              .addContainerGap()
              .addGroup(ZoekAanvraagTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(infoLabelART, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                .addGroup(ZoekAanvraagTabLayout.createSequentialGroup()
                  .addComponent(rijksnumStudentLabelART)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(studentenDropBoxART, 0, 514, Short.MAX_VALUE))
                .addComponent(gegevensPanelART, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(ZoekAanvraagTabLayout.createSequentialGroup()
              .addGap(26, 26, 26)
              .addComponent(verwijderLinkLabelART, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(120, Short.MAX_VALUE))
    );
    ZoekAanvraagTabLayout.setVerticalGroup(
      ZoekAanvraagTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(ZoekAanvraagTabLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(infoLabelART, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(ZoekAanvraagTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(rijksnumStudentLabelART)
          .addComponent(studentenDropBoxART, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(gegevensPanelART, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(verwijderLinkLabelART, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(boodschapLabelART, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(890, Short.MAX_VALUE))
    );

    FormulierScherm.addTab("Aanvragen raadplegen", ZoekAanvraagTab);

    UitloggenTab.setBackground(new java.awt.Color(255, 255, 255));

    uitloggenLinkLabel.setForeground(java.awt.Color.blue);
    uitloggenLinkLabel.setText("<html><u>Log me uit</u></html>");
    uitloggenLinkLabel.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        uitloggenLinkLabelMouseClicked(evt);
      }
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        uitloggenLinkLabelMouseEntered(evt);
      }
      public void mouseExited(java.awt.event.MouseEvent evt) {
        uitloggenLinkLabelMouseExited(evt);
      }
    });

    javax.swing.GroupLayout UitloggenTabLayout = new javax.swing.GroupLayout(UitloggenTab);
    UitloggenTab.setLayout(UitloggenTabLayout);
    UitloggenTabLayout.setHorizontalGroup(
      UitloggenTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(UitloggenTabLayout.createSequentialGroup()
        .addGap(30, 30, 30)
        .addComponent(uitloggenLinkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(712, Short.MAX_VALUE))
    );
    UitloggenTabLayout.setVerticalGroup(
      UitloggenTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(UitloggenTabLayout.createSequentialGroup()
        .addGap(26, 26, 26)
        .addComponent(uitloggenLinkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(1176, Short.MAX_VALUE))
    );

    FormulierScherm.addTab("Uitloggen", UitloggenTab);

    MainPanel.add(FormulierScherm, "card2");

    AdminScherm.setBackground(new java.awt.Color(255, 255, 255));
    AdminScherm.setPreferredSize(new java.awt.Dimension(800, 800));

    exporteerKnopAdmin.setText("Exporteer wachtlijsten");
    exporteerKnopAdmin.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        exporteerKnopAdminActionPerformed(evt);
      }
    });

    sorteerKnopAdmin.setText("Sorteer wachtlijsten");
    sorteerKnopAdmin.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        sorteerKnopAdminActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(30, 30, 30)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(exporteerKnopAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(sorteerKnopAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap(38, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(25, 25, 25)
        .addComponent(exporteerKnopAdmin)
        .addGap(18, 18, 18)
        .addComponent(sorteerKnopAdmin)
        .addContainerGap(60, Short.MAX_VALUE))
    );

    wachtlijstScrollPane.setViewportView(jList1);

    wachtlijstLadenKnop.setText("Laden");
    wachtlijstLadenKnop.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        wachtlijstLadenKnopActionPerformed(evt);
      }
    });

    wachtLijstNaamLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    wachtLijstNaamLabel.setText("Bestandsnaam:");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(wachtLijstNaamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(wachtLijstNaamVeld, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(wachtlijstLadenKnop, javax.swing.GroupLayout.Alignment.TRAILING))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(wachtlijstScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(27, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGap(43, 43, 43)
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(wachtLijstNaamVeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(wachtLijstNaamLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(wachtlijstLadenKnop))
          .addComponent(wachtlijstScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(53, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout AdminSchermLayout = new javax.swing.GroupLayout(AdminScherm);
    AdminScherm.setLayout(AdminSchermLayout);
    AdminSchermLayout.setHorizontalGroup(
      AdminSchermLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(AdminSchermLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(23, Short.MAX_VALUE))
    );
    AdminSchermLayout.setVerticalGroup(
      AdminSchermLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(AdminSchermLayout.createSequentialGroup()
        .addGap(32, 32, 32)
        .addGroup(AdminSchermLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(340, Short.MAX_VALUE))
    );

    MainPanel.add(AdminScherm, "card5");

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    getContentPane().add(MainPanel, gridBagConstraints);

    pack();
  }// </editor-fold>//GEN-END:initComponents
       
    /*
     * Methode dat de actie bepaalt bij het selecteren van een item uit
     * tabel met scholen
     */
    private void indienenKnopVFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indienenKnopVFTActionPerformed
        if(studentenDropBoxVFT.getSelectedItem() == null 
           || scholenTabel.getSelectedRow() < 0
           || aanvraagnummerVeldVFT.getText().equals("")) {
                    boodschapLabelVFT.setForeground(Color.red);
                    boodschapLabelVFT.setText("Maak een selectie!");
        } else {
            int aanvraagnummer = Integer.parseInt(aanvraagnummerVeldVFT.getText());
            Student student = main.ophalenStudent(studentenDropBoxVFT.getSelectedItem().toString());
            int schoolID = (int)scholenTabel.getValueAt(scholenTabel.getSelectedRow(), 3);
            if (main.schoolIsAfgewezen(schoolID, aanvraagnummer)) {
                    boodschapLabelVFT.setForeground(Color.red);
                    boodschapLabelVFT.setText("<html>U werd al afgewezen voor deze school! "
                                   + "<br/>Gelieve een andere school te selecteren.</html>");
            } else try {
                if(main.indienenVoorkeur(aanvraagnummer, student, schoolID)
                        && !main.schoolIsAfgewezen(schoolID, aanvraagnummer)) {
                    boodschapLabelVFT.setForeground(Color.green);
                    boodschapLabelVFT.setText("<html>U heeft uw voorkeur succesvol ingediend! "
                            + "<br/>Je kan je aanvragen raadplegen onder 'Aanvragen'.</html>");
                }  else {
                    boodschapLabelVFT.setForeground(Color.red);
                    boodschapLabelVFT.setText("Fout!");
                }
            } catch (DBException ex) {
                boodschapLabelVFT.setForeground(Color.red);
                boodschapLabelVFT.setText("U heeft al voor deze school gekozen!");
            }
        }
    }//GEN-LAST:event_indienenKnopVFTActionPerformed
    
    /*
     * Methode dat de actie bepaalt bij klikken op 'Indienen' onder de tab
     * 'Aanmeldingsformulier'
     */
    private void indienenKnopAFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indienenKnopAFTActionPerformed
      if(naamStudentVeldAFT.getText().equals("")){
        boodschapLabelAFT.setText("Maak een selectie!");
        boodschapLabelAFT.setForeground(Color.red);
      }
      else {
        Student s = main.ophalenStudent(studentenDropBoxAFT.getSelectedItem().toString());
        ToewijzingsAanvraag ta = new ToewijzingsAanvraag(main.keyNieuweAanvraag(), 
                                                         s.getRijksregisterNummer(), 
                                                         s.getRijksregisterNummerOuder());
        if(main.addAanvraag(ta)){
            boodschapLabelAFT.setForeground(Color.green);
            boodschapLabelAFT.setText("<html>U heef zich succesvol aangemeld! "
                + "<br/> Je kan je aanvragen raadplegen onder 'Aanvragen'.</html>");
        } else {
            boodschapLabelAFT.setText("U heeft al een aanvraag gedaan.");
            boodschapLabelAFT.setForeground(Color.red);
        }
      }
    }//GEN-LAST:event_indienenKnopAFTActionPerformed

    /*
     * Methode dat de actie bepaalt bij het tijpen van een zoekwoord onder 
     * de tab 'Voorkeurformulier'
     */
    private void zoekwoordVeldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zoekwoordVeldKeyReleased
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(((DefaultTableModel) scholenTabel.getModel())); 
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + zoekwoordVeld.getText()));
        scholenTabel.setRowSorter(sorter);
    }//GEN-LAST:event_zoekwoordVeldKeyReleased
    
    /*
     * Methode dat de actie bepaalt bij het zweven over 'Activeer' in het
     * aanmeldingsscherm
     */
    private void activeerLinkLabelISMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activeerLinkLabelISMouseEntered
        setCursor(Cursor.HAND_CURSOR);
    }//GEN-LAST:event_activeerLinkLabelISMouseEntered
    
    /*
     * Methode dat de actie bepaalt bij het niet zweven over 'Activeer' in het
     * aanmeldingsscherm
     */
    private void activeerLinkLabelISMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activeerLinkLabelISMouseExited
        setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_activeerLinkLabelISMouseExited
    
    /*
     * Methode dat de actie bepaalt bij klikken op 'Activeer' in het
     * aanmeldingsscherm
     */
    private void activeerLinkLabelISMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activeerLinkLabelISMouseClicked
        ActiveerScherm.setVisible(true);
        InlogScherm.setVisible(false);
        rijksnumVeldAS.setText("");
        naamVeldAS.setText("");
        voornaamVeldAS.setText("");
        emailVeldAS.setText("");
        adresVeldAS.setText("");
        boodschapLabelAS.setText("");
    }//GEN-LAST:event_activeerLinkLabelISMouseClicked
    
    /*
     * Methode dat de actie bepaalt bij het zweven over 'Terug' in het
     * aanmeldingsscherm
     */
    private void terugLinkLabelASMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_terugLinkLabelASMouseEntered
        setCursor(Cursor.HAND_CURSOR);
    }//GEN-LAST:event_terugLinkLabelASMouseEntered

    /*
     * Methode dat de actie bepaalt bij het zweven over 'Terug' in het
     * activeerscherm
     */
    private void terugLinkLabelASMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_terugLinkLabelASMouseExited
        setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_terugLinkLabelASMouseExited

    /*
     * Methode dat de actie bepaalt bij het niet zweven over 'Terug' in het
     * activeerscherm
     */
    private void terugLinkLabelASMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_terugLinkLabelASMouseClicked
        ActiveerScherm.setVisible(false);
        InlogScherm.setVisible(true);
        gebrVeldIS.setText("");
        passVeldIS.setText("");
        boodschapLabelIS.setText("");
    }//GEN-LAST:event_terugLinkLabelASMouseClicked

    /*
     * Methode dat de actie bepaalt bij het klikken op 'Terug' in het
     * activeerscherm
     */
    private void activeerKnopASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeerKnopASActionPerformed
       
            String rnouder = rijksnumVeldAS.getText();
            if(main.activeren(rnouder)) {
                boodschapLabelAS.setText("<html>Account succesvol aangemaakt. U ontangt van ons "
                                + "<br/>binnenkort een email met uw login gegevens.</html>");
                boodschapLabelAS.setForeground(Color.green);
            } else if (naamVeldAS.getText().equals("")) {
                boodschapLabelAS.setText("<html>U moet eerst een rijksregisternummer ingeven!</html>");
                boodschapLabelAS.setForeground(Color.red);
            } else { 
                boodschapLabelAS.setText("<html>U heeft al een account aangemaakt!</html>");
                boodschapLabelAS.setForeground(Color.red);
            }  
    }//GEN-LAST:event_activeerKnopASActionPerformed
    
    /*
     * Methode dat de actie bepaalt bij klikken op 'Inloggen' in het
     * aanmeldingsscherm
     */

    private void inlogKnopISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inlogKnopISActionPerformed
        /*
         * Gegevens vergelijken met de gegevens van de databank
         * Indien de juiste gebruikersnaam en wachtwoord werden ingegeven, wordt
         * de knop 'Doorgaan' beschikbaar en een groene boodschaap 'U bent
         * ingelogd!' verscijnt
         * Indien de gegevens niet kloppen wordt de boodschap 'Verkeerde 
         * gegevens.' weergegeven
         * Bij succes worden de gegevens van de gebruiker ingeladen en gebruikt
         * om de interface te bepalen
         */
        String gebrnaam = gebrVeldIS.getText();
        char[] passArray = passVeldIS.getPassword();
        //inloggen met verkeerde gegevens
	TypeGebruiker type = main.inloggen(gebrnaam, passArray);
	switch(type) {
	  case ADMIN: boodschapLabelIS.setText("Ingelogd als administrator.");
		      boodschapLabelIS.setForeground(Color.green);
		      doorgaanKnopIS.setEnabled(true);
		      InlogScherm.getRootPane().setDefaultButton(doorgaanKnopIS);
		      break;
	  case OUDER: boodschapLabelIS.setText("U bent ingelolgd.");
		      boodschapLabelIS.setForeground(Color.green);
		      doorgaanKnopIS.setEnabled(true);
		      InlogScherm.getRootPane().setDefaultButton(doorgaanKnopIS);

		      /* 
		       * Gegevens van ouder automatisch aanvullen in de 
		       * 'Aanmeldingsformulier'-tab
		       */
		      gebruiker = main.ophalenOuder(gebrnaam, passArray);
		      naamOuderVeldAFT.setText(gebruiker.getNaam());
		      voornaamOuderVeldAFT.setText(gebruiker.getVoornaam());
		      emailVeldAFT.setText(gebruiker.getEmail());
		      adresVeldAFT.setText(gebruiker.getStraat() + ", " + gebruiker.getGemeente());
		      rijksnumOuderVeldAFT.setText(gebruiker.getRijksregisterNummer());

		      /* 
		       * Dropbox items toevoegen in 'Voorkeurformulier'-tab en 
		       * 'Aanvragen raadplegen'-tab en in 'Aanmeldigsformulier'-tab
		       */
		      studentenDropBoxAFT.insertItemAt("", 0);
		      studentenDropBoxART.insertItemAt("", 0);
		      studentenDropBoxVFT.insertItemAt("", 0);           
		      main.ophalenKinderen(gebruiker.getRijksregisterNummer()).stream().map((s) -> {
			  studentenDropBoxAFT.addItem(s.getRijksregisterNummer());
			  return s;
		      }).map((s) -> {
			  studentenDropBoxART.addItem(s.getRijksregisterNummer());
			  return s;
		      }).forEachOrdered((s) -> {
			  studentenDropBoxVFT.addItem(s.getRijksregisterNummer());
		      });
		      break;
	    default:  boodschapLabelIS.setText("Verkeerde gegevens.");
		      boodschapLabelIS.setForeground(Color.red);
		      doorgaanKnopIS.setEnabled(false);	
		      break;
	}
    }//GEN-LAST:event_inlogKnopISActionPerformed

    /*
     * Methode dat de actie bepaalt bij klikken op 'Doorgaan' in het
     * aanmeldingsscherm
     */
    private void doorgaanKnopISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doorgaanKnopISActionPerformed
        if(gebruiker == null) {
	  AdminScherm.setVisible(true);
	  InlogScherm.setVisible(false);
	  ActiveerScherm.setVisible(false);
	  FormulierScherm.setVisible(false);
	} else {
	  ActiveerScherm.setVisible(false);
	  InlogScherm.setVisible(false);
	  FormulierScherm.setVisible(true);
	  FormulierScherm.setSelectedComponent(HomeTab);
	  PersoonlijkeJlabel.setText("Hallo " + gebruiker.getVoornaam() + " " 
				      + gebruiker.getNaam() + ".");
	}
    }//GEN-LAST:event_doorgaanKnopISActionPerformed

    /*
     * Methode dat de actie bepaalt bij afsluiten
     */
    private void onClose(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onClose
      
    }//GEN-LAST:event_onClose
    
    /*
     * Methode dat de actie bepaalt bij het opzoeken van een rijksregisternummer
     * in het activeerscherm
     */
    private void rijksnumVeldASKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rijksnumVeldASKeyReleased
        String rnouder = rijksnumVeldAS.getText();
        Ouder o = main.ophalenOuder(rnouder);
        if(o != null) {
            naamVeldAS.setText(o.getVoornaam());
            voornaamVeldAS.setText(o.getNaam());
            emailVeldAS.setText(o.getEmail());
            adresVeldAS.setText(o.getStraat() + ", " + o.getGemeente());
        } else {
          naamVeldAS.setText("");
          voornaamVeldAS.setText("");
          emailVeldAS.setText("");
          adresVeldAS.setText("");
        }
    }//GEN-LAST:event_rijksnumVeldASKeyReleased

    /*
     * Methode dat de actie bepaalt bij het maken van een selectie 
     * van een student onder de tab 'Aanmeldingsformulier'
     */
    private void studentenDropBoxAFTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_studentenDropBoxAFTItemStateChanged
        Student s = null;
        if(studentenDropBoxAFT.getItemCount() > 0) {
            s = main.ophalenStudent(
                    studentenDropBoxAFT.getSelectedItem().toString()
            );
        }
        if(s != null) {
            naamStudentVeldAFT.setText(s.getNaam());
            voornaamStudentVeldAFT.setText(s.getVoornaam());
            telnumVeldAFT.setText(s.getTelefoonnummer());
        } else {
            naamStudentVeldAFT.setText("");
            voornaamStudentVeldAFT.setText("");
            telnumVeldAFT.setText("");
        }
        boodschapLabelAFT.setText("");
    }//GEN-LAST:event_studentenDropBoxAFTItemStateChanged

    /*
     * Methode dat de actie bepaalt bij het maken van een selectie 
     * van een student onder de tab 'Aanvragen raadplegen'
     */
    private void studentenDropBoxARTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_studentenDropBoxARTItemStateChanged
        ToewijzingsAanvraag ta = null;
        if(studentenDropBoxART.getItemCount() > 0)
            ta = main.ophalenAanvraag(studentenDropBoxART.getSelectedItem().toString());
        if(ta == null && studentenDropBoxART.getSelectedIndex() > 0) {
            aanvraagnummerLabelOut.setText("");
            statusLabelOut.setText("");
            tijdstipLabelOut.setText("");
            eersteVoorkeurLabelOut.setText("");
            boodschapLabelART.setText("De aanvraag werd niet gevonden!");
            boodschapLabelART.setForeground(Color.red);
        } else if (ta == null || studentenDropBoxART.getSelectedIndex() == 0) {
            aanvraagnummerLabelOut.setText("");
            statusLabelOut.setText("");
            tijdstipLabelOut.setText("");
            eersteVoorkeurLabelOut.setText("");
            boodschapLabelART.setText("");
        } else {
            boodschapLabelART.setText("");
            aanvraagnummerLabelOut.setText(String.valueOf(ta.getToewijzingsAanvraagNummer()));
            statusLabelOut.setText(String.valueOf(ta.getStatus()));
            DateTimeFormatter df
                    = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
            String date = df.format(ta.getAanmeldingsTijdstip());
            tijdstipLabelOut.setText(date);
            int voorkeur = ta.getVoorkeur();
            if(voorkeur == 0)
                eersteVoorkeurLabelOut.setText("Je kan je voorkeur "
                                         + "aanpassen vóór " + main.getHuidigeDeadline());
            else
                eersteVoorkeurLabelOut.setText(main.ophalenSchool(voorkeur).toString());
        }
        
    }//GEN-LAST:event_studentenDropBoxARTItemStateChanged

    /*
     * Methode dat de actie bepaalt bij het maken van een selectie 
     * van een student onder de tab 'Voorkeurformulier'
     */
    private void studentenDropBoxVFTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_studentenDropBoxVFTItemStateChanged
        ToewijzingsAanvraag ta = null;
        if(studentenDropBoxVFT.getItemCount() > 0) {
            ta = main.ophalenAanvraag(
                studentenDropBoxVFT.getSelectedItem().toString()
            );
        } 
        if(ta == null) {
            aanvraagnummerVeldVFT.setText("");
        } else {
            aanvraagnummerVeldVFT.setText(
                    String.valueOf(ta.getToewijzingsAanvraagNummer())
            );
        }
    }//GEN-LAST:event_studentenDropBoxVFTItemStateChanged

    /*
     * Methode dat de actie bepaalt bij het selecteren van een tab
     */
    private void FormulierSchermStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_FormulierSchermStateChanged
        if(gebruiker != null) {
            studentenDropBoxAFT.setSelectedIndex(0);
            studentenDropBoxVFT.setSelectedIndex(0);
            studentenDropBoxART.setSelectedIndex(0);
            scholenTabel.clearSelection();
            boodschapLabelAFT.setText("");
            boodschapLabelVFT.setText("");
            boodschapLabelART.setText("");
        }
    }//GEN-LAST:event_FormulierSchermStateChanged

    /*
     * Methode dat de actie bepaalt bij het zweven over 'VERWIJDER' onder de
     * tab 'Aanvragen raadplegen'
     */
    private void verwijderLinkLabelARTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verwijderLinkLabelARTMouseEntered
        setCursor(Cursor.HAND_CURSOR);
    }//GEN-LAST:event_verwijderLinkLabelARTMouseEntered

    /*
     * Methode dat de actie bepaalt bij het niet zweven over 'VERWIJDER' onder de
     * tab 'Aanvragen raadplegen'
     */
    private void verwijderLinkLabelARTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verwijderLinkLabelARTMouseExited
        setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_verwijderLinkLabelARTMouseExited

    /*
     * Methode dat de actie bepaalt bij klikken op 'VERWIJDER' onder de tab
     * 'Aanvragen raadplegen'
     */
    private void verwijderLinkLabelARTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verwijderLinkLabelARTMouseClicked
        int aanvraagnummer = Integer.parseInt(aanvraagnummerLabelOut.getText());
        if(main.verwijderAanvraag(aanvraagnummer)) {
            studentenDropBoxART.setSelectedIndex(0);
            boodschapLabelART.setText("Aanvraag verwijderd!");
            boodschapLabelART.setForeground(Color.red);
        } 
    }//GEN-LAST:event_verwijderLinkLabelARTMouseClicked

    private void exporteerKnopAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exporteerKnopAdminActionPerformed
           
    }//GEN-LAST:event_exporteerKnopAdminActionPerformed

    private void uitloggenLinkLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uitloggenLinkLabelMouseEntered
        setCursor(Cursor.HAND_CURSOR);
    }//GEN-LAST:event_uitloggenLinkLabelMouseEntered

    private void uitloggenLinkLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uitloggenLinkLabelMouseExited
        setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_uitloggenLinkLabelMouseExited

    private void uitloggenLinkLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uitloggenLinkLabelMouseClicked
        InlogScherm.setVisible(true);
        doorgaanKnopIS.setEnabled(false);
        gebrVeldIS.setText("");
        passVeldIS.setText("");
        boodschapLabelIS.setText("");
        studentenDropBoxVFT.removeAllItems();
        studentenDropBoxAFT.removeAllItems();
        studentenDropBoxART.removeAllItems();
        this.main = new Main();
        this.gebruiker = null;
    }//GEN-LAST:event_uitloggenLinkLabelMouseClicked

    private void sorteerKnopAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sorteerKnopAdminActionPerformed
        main.sorteerAlgoritme();
    }//GEN-LAST:event_sorteerKnopAdminActionPerformed

    private void wachtlijstLadenKnopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wachtlijstLadenKnopActionPerformed
        int schoolID = Integer.parseInt(wachtLijstNaamVeld.getText());
        School s = main.ophalenSchool(schoolID);
        DefaultListModel dlm = new DefaultListModel();
        int i = 1;
        for(ToewijzingsAanvraag ta : s.getWachtLijst()) {
            dlm.addElement("(" + i + ") " + ta.toString());
            i++;
        }
        jList1.setModel(dlm);
    }//GEN-LAST:event_wachtlijstLadenKnopActionPerformed

    private void volgendeTabKnopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volgendeTabKnopActionPerformed
        FormulierScherm.setSelectedComponent(AanmeldingsFormulierTab);
    }//GEN-LAST:event_volgendeTabKnopActionPerformed

    

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel AanmeldingsFormulierTab;
  private javax.swing.JPanel ActiveerScherm;
  private javax.swing.JPanel AdminScherm;
  private javax.swing.JLabel AlgemeneTekstOuders;
  private javax.swing.JTabbedPane FormulierScherm;
  private javax.swing.JPanel HomeTab;
  private javax.swing.JPanel InlogScherm;
  private javax.swing.JPanel MainPanel;
  private javax.swing.JLabel PersoonlijkeJlabel;
  private javax.swing.JPanel UitloggenTab;
  private javax.swing.JPanel VoorkeurFormulierTab;
  private javax.swing.JPanel ZoekAanvraagTab;
  private javax.swing.JLabel aanvraagNummerLabelVFT;
  private javax.swing.JLabel aanvraagnummerLabelART;
  private javax.swing.JLabel aanvraagnummerLabelOut;
  private javax.swing.JTextField aanvraagnummerVeldVFT;
  private javax.swing.JButton activeerKnopAS;
  private javax.swing.JLabel activeerLinkLabelIS;
  private javax.swing.JLabel adresLabelAFT;
  private javax.swing.JLabel adresLabelAS;
  private javax.swing.JTextField adresVeldAFT;
  private javax.swing.JTextField adresVeldAS;
  private javax.swing.JLabel boodschapLabelAFT;
  private javax.swing.JLabel boodschapLabelART;
  private javax.swing.JLabel boodschapLabelAS;
  private javax.swing.JLabel boodschapLabelIS;
  private javax.swing.JLabel boodschapLabelVFT;
  private javax.swing.JButton doorgaanKnopIS;
  private javax.swing.JLabel eersteVoorkeurLabel;
  private javax.swing.JLabel eersteVoorkeurLabelOut;
  private javax.swing.JLabel emailLabelAFT;
  private javax.swing.JLabel emailLabelAS;
  private javax.swing.JTextField emailVeldAFT;
  private javax.swing.JTextField emailVeldAS;
  private javax.swing.JButton exporteerKnopAdmin;
  private javax.swing.JLabel gebrLabelAS;
  private javax.swing.JTextField gebrVeldIS;
  private javax.swing.JPanel gegevensOuderAFT;
  private javax.swing.JPanel gegevensOuderAS;
  private javax.swing.JPanel gegevensPanelART;
  private javax.swing.JPanel gegevensStudentAFT;
  private javax.swing.JButton indienenKnopAFT;
  private javax.swing.JButton indienenKnopVFT;
  private javax.swing.JLabel infoLabelART;
  private javax.swing.JLabel infoLabelVFT;
  private javax.swing.JButton inlogKnopIS;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JList<String> jList1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JLabel logoLabel;
  private javax.swing.JLabel logoLabel1;
  private javax.swing.JLabel naamLabelAS;
  private javax.swing.JLabel naamOuderLabelAFT;
  private javax.swing.JTextField naamOuderVeldAFT;
  private javax.swing.JLabel naamStudentLabelAFT;
  private javax.swing.JTextField naamStudentVeldAFT;
  private javax.swing.JTextField naamVeldAS;
  private javax.swing.JLabel passLabelIS;
  private javax.swing.JPasswordField passVeldIS;
  private javax.swing.JLabel rijksnumLabelAS;
  private javax.swing.JLabel rijksnumOuderLabelAFT;
  private javax.swing.JTextField rijksnumOuderVeldAFT;
  private javax.swing.JLabel rijksnumStudentLabelAFT;
  private javax.swing.JLabel rijksnumStudentLabelART;
  private javax.swing.JLabel rijksnumStudentLabelVFT;
  private javax.swing.JTextField rijksnumVeldAS;
  private javax.swing.JScrollPane scholenScrollPane;
  private javax.swing.JTable scholenTabel;
  private javax.swing.JLabel selectieBoodschapLabel;
  private javax.swing.JButton sorteerKnopAdmin;
  private javax.swing.JLabel statusLabel;
  private javax.swing.JLabel statusLabelOut;
  private javax.swing.JComboBox<String> studentenDropBoxAFT;
  private javax.swing.JComboBox<String> studentenDropBoxART;
  private javax.swing.JComboBox<String> studentenDropBoxVFT;
  private javax.swing.JLabel telnumLabelAFT;
  private javax.swing.JTextField telnumVeldAFT;
  private javax.swing.JLabel terugLinkLabelAS;
  private javax.swing.JLabel tijdstipLabel;
  private javax.swing.JLabel tijdstipLabelOut;
  private javax.swing.JLabel uitloggenLinkLabel;
  private javax.swing.JLabel verwijderLinkLabelART;
  private javax.swing.JButton volgendeTabKnop;
  private javax.swing.JLabel voornaamLabelAS;
  private javax.swing.JLabel voornaamOuderLabelAFT;
  private javax.swing.JTextField voornaamOuderVeldAFT;
  private javax.swing.JLabel voornaamStudentLabelAFT;
  private javax.swing.JTextField voornaamStudentVeldAFT;
  private javax.swing.JTextField voornaamVeldAS;
  private javax.swing.JLabel waarschuwingLabelAFT;
  private javax.swing.JLabel wachtLijstNaamLabel;
  private javax.swing.JTextField wachtLijstNaamVeld;
  private javax.swing.JButton wachtlijstLadenKnop;
  private javax.swing.JScrollPane wachtlijstScrollPane;
  private javax.swing.JLabel zoekwoordLabel;
  private javax.swing.JTextField zoekwoordVeld;
  // End of variables declaration//GEN-END:variables
}
